let shopData = [
  {
    id: 1,
    name: "Bánh mì Bò sốt Tiêu đen",
    des: "",
    img: "./image/banh-mi-bo-sot-tieu-den.jpg",
    price: 30000,
  },
  {
    id: 2,
    name: "Bánh mì Thịt nguội",
    des: "",
    img: "./image/banh-mi-thit-nguoi.jpg",
    price: 20000,
  },
  {
    id: 3,
    name: "Bánh mì Xá xíu",
    des: "",
    img: "./image/banh-mi-xa-xiu.jpg",
    price: 30000,
  },
  {
    id: 4,
    name: "Bánh mì Chả lụa",
    des: "",
    img: "./image/banh-mi-cha-lua.jpg",
    price: 25000,
  },
  {
    id: 5,
    name: "Bánh mì Doner Kebar",
    des: "",
    img: "./image/banh-mi-doner-kebar.jpg",
    price: 35000,
  },
  {
    id: 6,
    name: "Bánh mì Gà xé",
    des: "",
    img: "./image/banh-mi-ga-xe.jpg",
    price: 25000,
  },
  {
    id: 7,
    name: "Bánh mì Heo quay",
    des: "",
    img: "./image/banh-mi-heo-quay.jpg",
    price: 20000,
  },
  {
    id: 8,
    name: "Bánh mì Pate",
    des: "",
    img: "./image/banh-mi-pate.jpg",
    price: 25000,
  },
  {
    id: 9,
    name: "Bánh mì Xúc xích",
    des: "",
    img: "./image/banh-mi-xuc-xich.jpg",
    price: 15000,
  },
  {
    id: 10,
    name: "Trà Tắc",
    des: "",
    img: "./image/tra-tac.jpg",
    price: 12000,
  },
  {
    id: 11,
    name: "Trà Chanh",
    des: "",
    img: "./image/tra-chanh.jpg",
    price: 12000,
  },
  {
    id: 12,
    name: "Trà Đào",
    des: "",
    img: "./image/tra-dao.jpg",
    price: 12000,
  },
  {
    id: 13,
    name: "Coca",
    des: "",
    img: "./image/coca.jpg",
    price: 10000,
  },
  {
    id: 3,
    name: "Bò Húc",
    des: "",
    img: "./image/bo-huc.jpg",
    price: 12000,
  },
  {
    id: 3,
    name: "Nước lọc Lavie",
    des: "",
    img: "./image/lavie.jpg",
    price: 5000,
  },
];
